//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VSBS.ConsumeWinForms.MeuServico {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MeuServicoSoap", Namespace="http://tempuri.org/")]
    public partial class MeuServico : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaDeMontadorasOperationCompleted;
        
        private System.Threading.SendOrPostCallback PegaMontadoraPorCodigoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PegaMontadorPorFiltroDeNomeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MeuServico() {
            this.Url = global::VSBS.ConsumeWinForms.Properties.Settings.Default.VSBS_ConsumeWinForms_MeuServico_MeuServico;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event ListaDeMontadorasCompletedEventHandler ListaDeMontadorasCompleted;
        
        /// <remarks/>
        public event PegaMontadoraPorCodigoCompletedEventHandler PegaMontadoraPorCodigoCompleted;
        
        /// <remarks/>
        public event PegaMontadorPorFiltroDeNomeCompletedEventHandler PegaMontadorPorFiltroDeNomeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListaDeMontadoras", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Montadora[] ListaDeMontadoras() {
            object[] results = this.Invoke("ListaDeMontadoras", new object[0]);
            return ((Montadora[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaDeMontadorasAsync() {
            this.ListaDeMontadorasAsync(null);
        }
        
        /// <remarks/>
        public void ListaDeMontadorasAsync(object userState) {
            if ((this.ListaDeMontadorasOperationCompleted == null)) {
                this.ListaDeMontadorasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaDeMontadorasOperationCompleted);
            }
            this.InvokeAsync("ListaDeMontadoras", new object[0], this.ListaDeMontadorasOperationCompleted, userState);
        }
        
        private void OnListaDeMontadorasOperationCompleted(object arg) {
            if ((this.ListaDeMontadorasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaDeMontadorasCompleted(this, new ListaDeMontadorasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PegaMontadoraPorCodigo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Montadora PegaMontadoraPorCodigo(int id) {
            object[] results = this.Invoke("PegaMontadoraPorCodigo", new object[] {
                        id});
            return ((Montadora)(results[0]));
        }
        
        /// <remarks/>
        public void PegaMontadoraPorCodigoAsync(int id) {
            this.PegaMontadoraPorCodigoAsync(id, null);
        }
        
        /// <remarks/>
        public void PegaMontadoraPorCodigoAsync(int id, object userState) {
            if ((this.PegaMontadoraPorCodigoOperationCompleted == null)) {
                this.PegaMontadoraPorCodigoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPegaMontadoraPorCodigoOperationCompleted);
            }
            this.InvokeAsync("PegaMontadoraPorCodigo", new object[] {
                        id}, this.PegaMontadoraPorCodigoOperationCompleted, userState);
        }
        
        private void OnPegaMontadoraPorCodigoOperationCompleted(object arg) {
            if ((this.PegaMontadoraPorCodigoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PegaMontadoraPorCodigoCompleted(this, new PegaMontadoraPorCodigoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PegaMontadorPorFiltroDeNome", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Montadora[] PegaMontadorPorFiltroDeNome(string name) {
            object[] results = this.Invoke("PegaMontadorPorFiltroDeNome", new object[] {
                        name});
            return ((Montadora[])(results[0]));
        }
        
        /// <remarks/>
        public void PegaMontadorPorFiltroDeNomeAsync(string name) {
            this.PegaMontadorPorFiltroDeNomeAsync(name, null);
        }
        
        /// <remarks/>
        public void PegaMontadorPorFiltroDeNomeAsync(string name, object userState) {
            if ((this.PegaMontadorPorFiltroDeNomeOperationCompleted == null)) {
                this.PegaMontadorPorFiltroDeNomeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPegaMontadorPorFiltroDeNomeOperationCompleted);
            }
            this.InvokeAsync("PegaMontadorPorFiltroDeNome", new object[] {
                        name}, this.PegaMontadorPorFiltroDeNomeOperationCompleted, userState);
        }
        
        private void OnPegaMontadorPorFiltroDeNomeOperationCompleted(object arg) {
            if ((this.PegaMontadorPorFiltroDeNomeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PegaMontadorPorFiltroDeNomeCompleted(this, new PegaMontadorPorFiltroDeNomeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Montadora {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ListaDeMontadorasCompletedEventHandler(object sender, ListaDeMontadorasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaDeMontadorasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaDeMontadorasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Montadora[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Montadora[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void PegaMontadoraPorCodigoCompletedEventHandler(object sender, PegaMontadoraPorCodigoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PegaMontadoraPorCodigoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PegaMontadoraPorCodigoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Montadora Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Montadora)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void PegaMontadorPorFiltroDeNomeCompletedEventHandler(object sender, PegaMontadorPorFiltroDeNomeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PegaMontadorPorFiltroDeNomeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PegaMontadorPorFiltroDeNomeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Montadora[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Montadora[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591